### ISSUE TITLE
Error when launching trainer in game

### ISSUE THREAD

**Issue by Garberr** [pierre-josselin/payday-2-ultimate-trainer-6#6]
Keep getting an this error whenever I try to launch ultimate trainer 6 in payday 2 I've done some researching & can't find a solution, any help is much appreciated!
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/d1d79392-6ec8-4f1a-ae89-fd5c3b1b761d)
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/59090ab5-ca72-4425-b157-3fdeed2bb753)

**Comment by adityaasoleh** [comment]
@Garberr make sure the node program is allowed by windows firewall, that's looks like your node program not allowed  yet by windows firewall, because i just checked all is good. Hope this answer can help you, thanks!

**Comment by pierre-josselin** [comment]
Indeed the server does not seem to be launched. When you launch the game, can you ALT+TAB and see if the server console launches correctly? Or if you have any error message?

**Comment by Garberr** [comment]
I have just went & uninstalled the ultimate trainer & the game entirely & reinstalled them by following each step on the video that's posted on GitHub & everything seems to be installed properly again but yet again the error is still occurring different error code same issue
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/0419dd86-8a87-48b6-a329-52862d494a43)

**Comment by pierre-josselin** [comment]
Just to be sure, did you restart your computer?

If you have restarted your computer and the problem persists, please follow these steps:

- Open _payday-2-ultimate-trainer-6-main_ in your mods folder
- In the Windows address bar, type cmd and press enter
- In the console that opens, type `node index.js run` and press enter
- Take a photo of the result and post it here

![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/70814177/15bbb9d5-47bc-458d-99f0-b3f83b329b00)

![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/70814177/99697632-83b6-4926-ab5a-c8188ae38b65)

This will help confirm the cause of the issue.

**Comment by Garberr** [comment]
No prompt popped up or anything this is what I am currently looking at I'll wait to do anything else, I assume it now might be fixed ? But I'll wait for a response
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/cbc81dd1-13eb-45fc-918e-525775218078)

**Comment by pierre-josselin** [comment]
Hi, could you please:

- Close the manually run console
- Replace _payday-2-ultimate-trainer-6-mod/classes/UT.lua_ with **[UT.lua](https://drive.google.com/file/d/1VoidGzOk5tbhHUb3RbHqFmtJpMMBsfg-/view?usp=sharing)**
- Start the game
- Take a picture of the console opened with the game

This should fix the problem or give an interesting error message.

Thank you for your patience and cooperation.

**Comment by Garberr** [comment]
Closed the run console window & then went & replaced the UT.Lua with the one you'd sent me & started the game & sadly the error is still occurring 
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/f62c0ba3-a31d-4579-a8ec-5a6c94ecc065)
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/925e5a93-cc22-4a2c-b765-e61980e11369)

**Comment by pierre-josselin** [comment]
As a temporary solution I suggest you [to manually run the server](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/issues/6#issuecomment-1657252697).

For my part I will try to understand what is causing the problem, but since I can't reproduce it, it's complicated!

**Comment by pierre-josselin** [comment]
If you want to do one last test for me:

- Create an empty `developer.txt` text file inside your mods folder
- Replace _payday-2-ultimate-trainer-6-mod/classes/UT.lua_ with this new [UT.lua](https://drive.google.com/file/d/1vnxI5YgH_nzZfO0NVkXxbk2kuMXlPT7V/view?usp=sharing)
- Start the game
- Take a picture of the console opened with the game

![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/70814177/431a231a-7ea6-4a7d-843e-24e9e35ac4e0)
This is not supposed to fix the problem but will necessarily open a console with the game. Hopefully it gives us more details...

**Comment by Garberr** [comment]
As of now I am able to use the trainer without any issues works like a charm, I'm still not %100 sure what exactly was the issue after a while with messing with the files trying to get it to work I simply uninstalled everything & rewatched the video over that is posted on here on how to install & carefully watching each step & then I'd realize I'd had a wrong node.js installed (32bit not 64) but after getting the correct one issue still was occurring so I went to see if there was newer/latest version of node.js which there is the one you have posted is node.js 18 & currently there is newer version which is node.js 20 which is what I'd installed upon doing so & completing the rest of install steps I started the game & just like that it worked like a charm haven't had any issues yet other than not receiving/unlocking any masks that I try to unlock but I can live without that. Just wanted to give an update & say thank for you all your hard work, time & efforts will be gladly enjoying this trainer now once again thank you !
![image](https://github.com/pierre-josselin/payday-2-ultimate-trainer-6/assets/133093220/bac80aea-32e7-4c37-970d-9174574c45e3)

**Comment by pierre-josselin** [comment]
Thanks you very much for the update, glad to see you can use it!  I'll use the details you provided to try to provide a solution for others people who  may encounter this kind of problem.
